version: "3"

services:
  python-microservice:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/python-microservice
    environment:
      FLASK_ENV: development

  redis:
    image: "redis:alpine"